# Generated by Django 3.0.2 on 2020-01-21 14:04

from django.db import migrations, models
from django.utils.text import slugify

class Migration(migrations.Migration):
    def forwards_func(apps, schema_editor):
        User = apps.get_model("account", "CustomUser")
        for instance in User.objects.all():
            if not instance.slug:
                email_name = instance.email.split('@')[0]
                instance.slug = slugify(email_name)
                instance.save()

    def reverse_func(apps, schema_editor):
        pass


    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.RunPython(forwards_func, reverse_func)
    ]
